--RF1
INSERT INTO A_PROVEEDOR (NIT, NOMBRE, CALIFICACION, TIPOPROVEEDOR)
VALUES (100000000,'Proveedor A', 3, 'General')
;


--RF2: 1) Debe existir una sucursal, un almacenamiento de la sucursal, un proveedor y opcionalmente una promoción
INSERT INTO A_PRODUCTO (CODIGO_DE_BARRAS, NOMBRE, MARCA, PRECIO_UNITARIO, VOLUMEN_EMPAQUETADO, PESO, PRECIO_UNIDAD_MEDIDA, CANTIDAD_PRESENTACION, UNIDAD_DE_MEDIDA, PRECIO, CATEGORIA, NIVEL_DE_REORDEN, NIT_PROVEEDOR)
VALUES ('1','Raid','Raid',20.5,23,50,2,1,'ml',1000,'De Aseo',50.0,100000000)
;

--RF3
INSERT INTO A_CLIENTE (CORREO, NOMBRE,PUNTOS_FIDELIZACION)
VALUES ('js.bravo@uniandes.edu.co','Juan Sebastian',0)
;
INSERT INTO A_PERSONANATURAL (NUMERO_IDENTIFICACION, TIPO_DOCUMENTO, CORREO_CLIENTE)
VALUES ('1018510315','CC','js.bravo@uniandes.edu.co')
;


--RF4
INSERT INTO A_LOCAL_VENTAS (ID_LOCALVENTAS)
VALUES (1)
;

INSERT INTO A_SUCURSAL (NOMBRE,DIRECCION,CIUDAD,ID_LOCALVENTAS)
VALUES ('SuperAndes 170', 'Calle 170 #57','Bogotá',1)
;

--RF5

INSERT INTO A_ALMACENAMIENTO
(ID_ALMACENAMIENTO, CATEGORIA, CAPACIDAD_VOLUMEN, CAPACIDAD_PESO, CANTIDAD_PRODUCTOS, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_CIUDAD)
VALUES (1,'Perecederos',500,500,0,'SuperAndes 170', 'Calle 170 #57','Bogotá');

INSERT INTO A_BODEGA
(ID_ALMACENAMIENTO,NOMBRE_BODEGA) VALUES (1,'Bodega_A')
;

--RF6

INSERT INTO A_ALMACENAMIENTO
(ID_ALMACENAMIENTO, CATEGORIA, CAPACIDAD_VOLUMEN, CAPACIDAD_PESO, CANTIDAD_PRODUCTOS, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_CIUDAD)
VALUES (2,'Perecederos',500,500,0,'SuperAndes 170', 'Calle 170 #57','Bogotá');

INSERT INTO A_ESTANTE
(ID_ALMACENAMIENTO,NOMBRE_ESTANTE,NIVEL_ABASTECIMIENTO) VALUES (2,'Estante_B',15.0)
;

--RF7

INSERT INTO A_PROMOCION (ID_PROMOCION, NIT_PROVEEDOR, TIPO_PROMOCION, NOMBRE_PROMOCION, CANTIDAD_PRODUCTOS, FECHA_INICIAL, FECHA_FINAL,DISPONIBLE)
  VALUES (1,100000000,'Pague a lleve b','nombre',1000,TO_DATE('01/10/2018', 'DD/MM/YYYY'),TO_DATE('03/10/2018', 'DD/MM/YYYY'),1)
  ;

  --RF8
  UPDATE A_PROMOCION SET DISPONIBLE=0 WHERE ID_PROMOCION = 1
  ;

  --RF9
  INSERT INTO A_PEDIDO (NUMERO_PEDIDO,NIT_PROVEEDOR,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,CIUDAD_SUCURSAL,CODIGO_DE_BARRAS_PRODUCTO,FECHA_ESPERADA,PRECIO,CANTIDAD_VOLUMEN)
  VALUES (1,100000000,'SuperAndes 170', 'Calle 170 #57','Bogotá','1',TO_DATE('03/10/2018', 'DD/MM/YYYY'),1000,150.5)
;
  --R10
 UPDATE A_ALMACENAMIENTO SET CANTIDAD_PRODUCTOS = (CANTIDAD_PRODUCTOS + 1)  WHERE (ID_ALMACENAMIENTO=1);
 UPDATE A_PEDIDO SET FECHA_ENTREGA = TO_DATE('03/10/2018', 'DD/MM/YYYY'), CALIDAD = 'Buena', CALIFICACION = '10' WHERE NUMERO_PEDIDO = 1
 ;

  --R11
  INSERT INTO A_FACTURA (NUMERO_FACTURA, FECHA_COMPRA, VALOR_BASE, DESCUENTO, IVA, VALOR_TOTAL, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_CIUDAD, CORREO_CLIENTE) VALUES (1, TO_DATE('03/10/2018', 'DD/MM/YYYY'), 100,10,16,96,'SuperAndes 170', 'Calle 170 #57','Bogotá','js.bravo@uniandes.edu.co');
  INSERT INTO A_FACTURA_PRODUCTO (NUMERO_FACTURA, CODIGO_DE_BARRAS, CANTIDAD) VALUES (1,'1',1);
UPDATE A_ALMACENAMIENTO SET CANTIDAD_PRODUCTOS = (CANTIDAD_PRODUCTOS - 1)  WHERE (ID_ALMACENAMIENTO=1);
