RFC1
---- MOSTRAR EL DINERO RECOLECTADO POR VENTAS EN CADA SUCURSAL DURANTE UN PERIODO DE TIEMPO Y EN EL AÑO CORRIDO

SELECT COUNT (VALOR_TOTAL) FROM A_FACTURA WHERE FECHA_COMPRA >= 'FECHA_INICIAL' AND 'FECHA_FINAL' >= FECHA_COMPRA GROUP BY NOMBRE_SUCURSAL;

RFC2
--- MOSTRAR LAS 20 PROMOCIONES MÁS POPULARES.

SELECT CODIGO_DE_BARRAS,COUNT(ID_PROMOCION) FROM
(
SELECT A.CODIGO_DE_BARRAS, A.CANTIDAD,B.ID_PROMOCION FROM (A_FACTURA_PRODCUTOS) A INNER JOIN (A_PRODUCTO) B WHERE A.CODIGO_DE_BARRAS = B.CODIGO_DE_BARRAS
)
GROUP BY CANTIDAD;

RFC3
---MOSTRAR EL ÍNDICE DE OCUPACIÓN DE CADA UNA DE BODEGAS Y ESTANTES DE UNA SUCURSAL

SELECT IDALMACENAMIENTO,NIVEL_ABASTECIMIENTO FROM A_ESTANTE;

RFC4
---MOSTRAR LOS PRODUCTOS QUE CUMPLEN CON CIERTA CARACTERÍSTICA

SELECT * FROM A_PRODUCTO WHERE <CONDICION> = <CONDICION>;

RFC5
--- MOSTRAR LAS COMPRAS HECHAS POR SUPERANDES A LOS PROVEEDORES
SELECT * FROM A_PEDIDO;

RFC6
--- MOSTRAR LAS VENTAS DE SUPERANDES A UN USUARIO DADO, EN UN RANGO DE FECHAS INDICADO.
SELECT * FROM A_FACTURA WHERE CORREO_CLIENTE = <CORREO_USUARIO> AND FECHA_COMPRA >= <FECHA_INICIAL> AND FECHA_COMPRA <= <FECHA_FINAL>: